site_name: FreeMoCap Documentation

theme:
  name: material
  logo: assets/fmc-logo-transparent-bkgd.png
  favicon: assets/skelly_freemocap_favicon.ico
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
#    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand

extra_css:
  - stylesheets/extra.css

custom_dir: overrides

nav:
  - Home: 'index.md'
  - About Us: 'about_us.md'
  - Getting Started: 
    - 'Basic Workflow': 'Tutorials/index.md'
    - 'Making your first Skelly': 'Tutorials/single_camera_recording.md'
    - 'Advanced Skeleton Wrangling': 'Tutorials/multi_camera_calibration.md'
  - Terminology: 'terminology/terminology.md'
  # - 'roadmap/roadmap.md'  # TODO - update this (or link to github project?)
  - 'privacy_policy.md'
  

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format 
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 3

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/freemocap

    - icon: fontawesome/brands/github
      link: https://github.com/freemocap/freemocap

    - icon: fontawesome/brands/discord
      link: https://discord.gg/SgdnzbHDTG

    - icon: fontawesome/brands/twitch
      link: https://twitch.tv/freemocap

    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/jonmatthis

plugins:
  - mkdocs-video
  - search

