site_name: FreeMoCap Documentation
repo_url: https://github.com/freemocap/freemocap

theme:
  name: material
  logo: assets/fmc-logo-transparent-bkgd.png
  favicon: assets/skelly_freemocap_favicon.ico
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


extra_css:
  - stylesheets/extra.css

#custom_dir: overrides

nav:
  - Home: 'index.md'
  - About Us: 'about_us.md'
  - Getting Started:
    - 'Basic Workflow': 'getting_started/index.md'
    - 'Installation': 'getting_started/installation.md'
    - Single-Camera Tutorial: 'getting_started/single_camera_recording.md'
    - Multi-Camera Tutorial: 'getting_started/multi_camera_calibration.md'
  - Contributing:
    - Contributing Guide: 'contributing/index.md'
    - Python Style Guide: 'contributing/python_code_style_guide.md'
  - Community:
    - Code of Conduct: 'community/code_of_conduct.md'
    - Privacy Policy: 'community/privacy_policy.md'

  

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format 
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
      baselevel: 2





extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/freemocap

    - icon: fontawesome/brands/github
      link: https://github.com/freemocap/freemocap

    - icon: fontawesome/brands/discord
      link: https://discord.gg/SgdnzbHDTG

    - icon: fontawesome/brands/twitch
      link: https://twitch.tv/freemocap

    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/jonmatthis

plugins:
  - mkdocs-video
  - search

