site_name: FreeMoCap Documentation

theme:
  name: material
  logo: assets/skelly_freemocap_logo.png
  favicon: assets/skelly_freemocap_favicon.ico
  features: 
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand

extra_css:
  - stylesheets/extra.css

nav:
   - 'index.md'
   - 'about_us.md'
   - 'how_to_guides.md'
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/freemocap

    - icon: fontawesome/brands/github
      link: https://github.com/freemocap/freemocap

    - icon: fontawesome/brands/discord
      link: https://discord.gg/SgdnzbHDTG

    - icon: fontawesome/brands/twitch
      link: https://twitch.tv/freemocap

    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/jonmatthis


